---
title: "Modeling"
author: "Carter Hall"
date: "2024-04-06"
output: html_document
---

## Package Imports

```{r}
library(MASS)
library(tidyverse)
library(car)
```

## Preprocessing

```{r}
cleanedData <- read_csv("data/college_data_cleaned.csv")
cleanedData <- cleanedData[,-c(4,17,18,ncol(cleanedData),65)]
cleanedData[(cleanedData == "NULL") | (cleanedData == "PrivacySuppressed")] <- NA

satMod <- lm(as.numeric(sat_avg) ~ as.numeric(admission_rate), data = na.omit(cleanedData))

cleanedData <- cleanedData %>% mutate(
  type_school = as.factor(type_school),
  degree_length = as.factor(degree_length),
  state_code.x = as.factor(state_code.x),
  REGION = as.factor(REGION),
  LOCALE = as.factor(LOCALE),
  degree_type = as.factor(degree_type),
  admission_rate = as.numeric(admission_rate),
  age_entry = as.numeric(age_entry),
  first_gen = as.numeric(first_gen),
  pct_domestic = as.numeric(pct_domestic),
  pct_grad_degree = as.numeric(pct_grad_degree),
  sat_avg = as.numeric(sat_avg),
  netprice_lowincome = as.numeric(netprice_lowincome),
  highest_degree = as.factor(highest_degree),
  med_fam_inc = as.numeric(med_fam_inc)) %>%
  mutate(
    admission_rate = ifelse(is.na(admission_rate), 
                            median(admission_rate,na.rm=T), admission_rate)) %>%
  mutate(
        sat_avg = ifelse(is.na(sat_avg), 
                     coef(satMod)[1] + coef(satMod)[2]*admission_rate,sat_avg),
    age_entry = ifelse(is.na(admission_rate), 
                            mean(age_entry,na.rm=T), age_entry),
    first_gen = ifelse(is.na(first_gen), 
                            mean(first_gen,na.rm=T), first_gen),
    med_fam_inc = ifelse(is.na(med_fam_inc), 
                            mean(med_fam_inc,na.rm=T), med_fam_inc),
    pct_grad_degree = ifelse(is.na(pct_grad_degree), 
                            mean(pct_grad_degree,na.rm=T), pct_grad_degree),
    pct_domestic = ifelse(is.na(pct_domestic), 
                            mean(pct_domestic,na.rm=T), pct_domestic),
    median_hh_income = ifelse(is.na(median_hh_income), 
                            median(median_hh_income,na.rm=T),median_hh_income),
    C150_POOLED = ifelse(is.na(C150_POOLED), 
                         median(C150_POOLED,na.rm=T),C150_POOLED),
    netprice_lowincome = ifelse(is.na(netprice_lowincome), 
                                median(netprice_lowincome,na.rm=T),
                                netprice_lowincome),
    room_and_board = ifelse(is.na(room_and_board), median(room_and_board,na.rm=T),
                            room_and_board),
    total_enrollment = ifelse(is.na(total_enrollment), 
                              median(total_enrollment,na.rm=T),total_enrollment),
    make_world_better_percent = ifelse(is.na(make_world_better_percent), 
                            median(make_world_better_percent,na.rm=T),
                            make_world_better_percent)
) %>% rename(
  "state_code" = "state_code.x",
  "region" = "REGION",
  "locale" = "LOCALE",
  "PacificIslander" = "Native Hawaiian / Pacific Islander",
  "AmericanIndian" = "American Indian / Alaska Native",
  "TwoOrMoreRaces" = "Two Or More Races",
  "graduation_rate" = "C150_POOLED"
) %>% mutate(
  hbcu = as.factor(hbcu),
  pbi = as.factor(pbi),
  annhi = as.factor(annhi),
  tribal = as.factor(tribal),
  AANAPII = as.factor(AANAPII),
  his = as.factor(his),
  nanti = as.factor(nanti),
  men_only = as.factor(men_only),
  women_only = as.factor(women_only),
  distance_only = as.factor(distance_only),
  pred_degree_type = as.factor(pred_degree_type),
  netprice_lowincome = as.numeric(netprice_lowincome),
  tuit_fte = as.numeric(tuit_fte),
  inexp_fte = as.numeric(inexp_fte),
  avg_fac_salary = as.numeric(avg_fac_salary),
  pct_ft_fac = as.numeric(pct_ft_fac),
  pct_pell = as.numeric(pct_pell),
  graduation_rate = as.numeric(graduation_rate),
  median_hh_income = as.numeric(median_hh_income),
  poverty_rate = as.numeric(poverty_rate),
  unemployment_rate = as.numeric(unemployment_rate)
) %>% mutate(
  Women = Women / total_enrollment,
  AmericanIndian = AmericanIndian / total_enrollment,
  Asian = Asian / total_enrollment,
  Black = Black / total_enrollment,
  Hispanic = Hispanic / total_enrollment,
  PacificIslander = PacificIslander / total_enrollment,
  White = White / total_enrollment,
  TwoOrMoreRaces = TwoOrMoreRaces / total_enrollment,
  Unknown = Unknown / total_enrollment
) %>% dplyr::select(
  -tribal,-cash_monitoring
) %>% mutate(
  unemployment_rate = unemployment_rate / 100,
  pct_grad_degree = pct_grad_degree / 100,
  make_world_better_percent = make_world_better_percent / 100,
  stem_percent = stem_percent / 100,
  pct_domestic = pct_domestic / 100
)

## Upload this dataset (write.csv)
cleanedData
cleanedData <- na.omit(cleanedData)
#write.csv(cleanedData,"data/cleanedData_411.csv")
```

## Helper Functions
```{r}
#' @title Analysis of Deviance for Full/Reduced GLMs
#' @description Give nested GLMs and return AOD test p-value
AODglms <- function(full, red) {
  return(
    pchisq(q = deviance(red) - deviance(full),
          df = red$df.residual-full$df.residual,lower=F)
  )
}

#' @title Compute RMSE
#' @description Compute root mean squared error (can be used for RMPSE)
RMSE.Carter <- function(pred, obs) {
  return(sqrt(mean((pred - obs)^2)))
}
```

## Modeling

### Train-Test Split for Cross Validation

```{r}
set.seed(704)
idxs <- sample(1:nrow(cleanedData),replace = F,size = 0.8*nrow(cleanedData))
train <- cleanedData[idxs,]
test  <- cleanedData[-idxs,]

```

```{r}
# Load in data
#train = readRDS('data/train_414.Rds')
#test = readRDS('data/test_414.Rds')
```

### Linear Regression 

```{r}
college.class<-sapply(train, class)
college.unique<-sapply(train, function(x)length(unique(x)))
num.cols<-college.class%in%c("integer", "numeric")&college.unique>1
college.data.num<-train[,num.cols]
corr.mat<-cor(college.data.num)
cor.thresh<-0.9 # Used to limit displayed matrix cuz it's kinda big
corr.mat.extreme.row<-apply(corr.mat, 1, function(x)sum(abs(x)>cor.thresh))>2
corr.mat.extreme.col<-apply(corr.mat, 2, function(x)sum(abs(x)>cor.thresh))>2
corr.extreme<-corr.mat[corr.mat.extreme.row,corr.mat.extreme.col]
corrplot::corrplot(corr.extreme, diag=F, type="lower", tl.cex=0.72)
```

```{r}
lmMod1 <- lm(early_career_pay ~ . -name-state-mid_career_pay-state_code
                        -`Total Minority`-out_of_state_total-`Non-Resident Foreign`
                        -in_state_total-region-Black-in_state_tuition-rank-poverty_rate
                        -pred_degree_type-highest_degree, 
   data = train)
summary(lmMod1)
vifslm1 <- vif(lmMod1)
vifslm1[order(vifslm1[,1],decreasing = T),]

plot(lmMod1)
bc <- boxCox(lmMod1)
bc$x[which.max(bc$y)] 
qqPlot(lmMod1)

boxTidwell(log(early_career_pay) ~ room_and_board + total_enrollment + ST_FIPS + admission_rate + sat_avg + first_gen + med_fam_inc + pct_domestic + median_hh_income, other.x = ~ degree_length + make_world_better_percent + stem_percent + degree_type + type_school + locale + hbcu + pbi + annhi + AANAPII + his + nanti + men_only + women_only + distance_only,  data=train)

numberzeros = colSums(train == 0)
View(numberzeros)

lmMod1b <- lm(log(early_career_pay) ~ . -name-state-mid_career_pay-state_code
                        -`Total Minority`-out_of_state_total-`Non-Resident Foreign`
                        -in_state_total-region-Black-in_state_tuition-rank-poverty_rate
                        -pred_degree_type-highest_degree+I(room_and_board^-2)-total_enrollment+log(total_enrollment)+I(admission_rate^(-1)),
   data = train)
summary(lmMod1b)
vif(lmMod1b)
plot(lmMod1b)
residualPlots(lmMod1b)

lmMod1c <- lm(log(early_career_pay) ~ . + I(asin(sqrt(Women))) + I(unemployment_rate^4)-name-state-mid_career_pay-state_code
                        -`Total Minority`-out_of_state_total-`Non-Resident Foreign`
                        -in_state_total-region-Black-in_state_tuition-rank-poverty_rate
                        -pred_degree_type-highest_degree,
   data = train)
summary(lmMod1c)
plot(lmMod1c)
```

```{r}
transformed.lm = lm(log(early_career_pay) ~ degree_length + room_and_board +
                      out_of_state_tuition +
                      make_world_better_percent + stem_percent + degree_type +
                      type_school + ST_FIPS + locale + hbcu + annhi + AANAPII +
                      his + nanti + men_only + women_only + admission_rate
                      + I(admission_rate^-1) + log(total_enrollment) +
                      sat_avg + distance_only + netprice_lowincome +
                      tuit_fte + inexp_fte + avg_fac_salary + pct_ft_fac +
                      pct_pell + graduation_rate + age_entry + first_gen +
                      pct_grad_degree + pct_domestic + I(pct_domestic^4) +
                      unemployment_rate +
                      Women + AmericanIndian + Asian + Hispanic +
                      PacificIslander + White + TwoOrMoreRaces + Unknown
                    , 
                    data=train)

X = model.matrix(transformed.lm)
```

```{r}
library(caret)
library(leaps)
K=10
X.og = model.matrix(log(early_career_pay) ~ . -name-state-mid_career_pay-state_code
                        -`Total Minority`-out_of_state_total-`Non-Resident Foreign`
                        -in_state_total-region-Black-in_state_tuition-rank-poverty_rate
                        -pred_degree_type-highest_degree, data=train)

set.seed(704)
getit <- train(log(early_career_pay) ~ . -name-state-mid_career_pay-state_code
                        -`Total Minority`-out_of_state_total-`Non-Resident Foreign`
                        -in_state_total-region-Black-in_state_tuition-rank-poverty_rate
                        -pred_degree_type-highest_degree, 
               data=train,
               method='leapSeq',
               tuneGrid=data.frame(nvmax = 1:50),
               trControl=trainControl(method='cv',
                                      number=K,
                                      returnResamp='all',
                                      selectionFunction='oneSE'))
coef(getit$finalModel, id=5)
set.seed(704)
stepwise.selection <- train(log(early_career_pay) ~ degree_length + room_and_board +
                      out_of_state_tuition +
                      make_world_better_percent + stem_percent + degree_type +
                      type_school + ST_FIPS + locale + hbcu + annhi + AANAPII +
                      his + nanti + men_only + women_only + admission_rate
                      + I(admission_rate^-1) + log(total_enrollment) +
                      sat_avg + distance_only + netprice_lowincome +
                      tuit_fte + inexp_fte + avg_fac_salary + pct_ft_fac +
                      pct_pell + graduation_rate + age_entry + first_gen +
                      pct_grad_degree + pct_domestic + I(pct_domestic^4) +
                      unemployment_rate +
                      Women + AmericanIndian + Asian + Hispanic +
                      PacificIslander + White + TwoOrMoreRaces + Unknown, 
                    data=train,
                      method='leapSeq',
                      tuneGrid=data.frame(nvmax = 1:50),
                      trControl=trainControl(method='cv',
                                             number=K,
                                             returnResamp='all',
                                             selectionFunction='oneSE')
                    )
stepwise.selection
coef(stepwise.selection$finalModel, id=6)
stepwise.model = lm(log(early_career_pay) ~ make_world_better_percent + 
                      stem_percent +
                       tuit_fte + avg_fac_salary + pct_pell + pct_domestic + 
                      I(pct_domestic^4),
                    data=train)
summary(stepwise.model)
plot(stepwise.model)
stepwise.preds = predict(stepwise.model, newdata = test)
stepwise.rmsep = RMSE(stepwise.preds, log(test$early_career_pay))
```

```{r}
library(glmnet)
# Fit LASSO Model
X.lasso = X[,-1]
fit.lasso <- glmnet(X.lasso, log(train$early_career_pay), alpha=1)
#plot(fit.lasso, label=TRUE, xvar='lambda')
lambda.lasso = fit.lasso$lambda
betahat.lasso = fit.lasso$beta
# plot standardized LASSO coefficients
nn <- nrow(X.lasso)
Xsd <- apply(X.lasso,2,sd) * sqrt((nn-1)/nn)
ysd = sd(train$early_career_pay) * sqrt((nn-1)/nn)
par(mar=c(5.1, 4.1, 4.1, 8.1), xpd=TRUE)
matplot(lambda.lasso, t(betahat.lasso * Xsd), type="l",
log="x", lwd=2,lty=1:5,col=1:6,
xlab=expression(lambda), ylab='Standardized Coefficients')
axis(3, at=lambda.lasso, labels=fit.lasso$df)
# perform CV to find optimal lambda
set.seed(704)
cv.lasso <- cv.glmnet(X, log(train$early_career_pay), alpha=1)
plot(cv.lasso)
lambda.lasso.chosen <- cv.lasso$lambda.1se
coef(fit.lasso, s=lambda.lasso.chosen)
X.test.lasso = model.matrix(log(early_career_pay) ~ degree_length + room_and_board +
                      out_of_state_tuition +
                      make_world_better_percent + stem_percent + degree_type +
                      type_school + ST_FIPS + locale + hbcu + annhi + AANAPII +
                      his + nanti + men_only + women_only + admission_rate
                      + I(admission_rate^-1) + log(total_enrollment) +
                      sat_avg + distance_only + netprice_lowincome +
                      tuit_fte + inexp_fte + avg_fac_salary + pct_ft_fac +
                      pct_pell + graduation_rate + age_entry + first_gen +
                      pct_grad_degree + pct_domestic + I(pct_domestic^4) +
                      unemployment_rate +
                      Women + AmericanIndian + Asian + Hispanic +
                      PacificIslander + White + TwoOrMoreRaces + Unknown, 
                      data=test)[,-1]
coef(fit.lasso, s=lambda.lasso.chosen)
lasso.preds = predict(fit.lasso, s=lambda.lasso.chosen, newx=X.test.lasso)
lasso.rmspe = RMSE(lasso.preds, log(test$early_career_pay))
```

```{r}
## lasso looks good but somethings up with these two...
# PCR
library(pls)
set.seed(704)
fit.pcr = pcr(log(early_career_pay) ~ degree_length + room_and_board +
                      out_of_state_tuition +
                      make_world_better_percent + stem_percent + degree_type +
                      type_school + ST_FIPS + locale + hbcu + annhi + AANAPII +
                      his + nanti + men_only + women_only + admission_rate
                      + I(admission_rate^-1) + log(total_enrollment) +
                      sat_avg + distance_only + netprice_lowincome +
                      tuit_fte + inexp_fte + avg_fac_salary + pct_ft_fac +
                      pct_pell + graduation_rate + age_entry + first_gen +
                      pct_grad_degree + pct_domestic + I(pct_domestic^4) +
                      unemployment_rate +
                      Women + AmericanIndian + Asian + Hispanic +
                      PacificIslander + White + TwoOrMoreRaces + Unknown, 
              data=train,
              scale=TRUE,
              validation = "CV",
              segments=10,
              segment.type='random'
)
par(mar=c(5.1, 4.1, 4.1, 7), xpd=T)
coefplot(fit.pcr,separate=FALSE, ncomp=1:5)
legend('right', col=1:5, lty=1:2,
legend=c("1 comp", "2 comp", "3 comp", "4 comp", "5 comp"),
bg='white', inset=c(-0.4,0))
ncomp.pcr1se = selectNcomp(fit.pcr,method="onesigma",plot=TRUE)
pcr.preds = predict(fit.pcr, newdata=test, ncomp=ncomp.pcr1se)
pcr.rmsep = RMSE(pcr.preds, log(test$early_career_pay))

# PLS
set.seed(704)
fit.pls = plsr(log(early_career_pay) ~ degree_length + room_and_board +
                      out_of_state_tuition +
                      make_world_better_percent + stem_percent + degree_type +
                      type_school + ST_FIPS + locale + hbcu + annhi + AANAPII +
                      his + nanti + men_only + women_only + admission_rate
                      + I(admission_rate^-1) + log(total_enrollment) +
                      sat_avg + distance_only + netprice_lowincome +
                      tuit_fte + inexp_fte + avg_fac_salary + pct_ft_fac +
                      pct_pell + graduation_rate + age_entry + first_gen +
                      pct_grad_degree + pct_domestic + I(pct_domestic^4) +
                      unemployment_rate +
                      Women + AmericanIndian + Asian + Hispanic +
                      PacificIslander + White + TwoOrMoreRaces + Unknown,
              data=train,
              scale=TRUE,
              validation = "CV",
              segments=10,
              segment.type='random',
              method='simpls'
)
ncomp.pls1se = selectNcomp(fit.pls,method="onesigma",plot=TRUE)
pls.preds = predict(fit.pls, newdata=test, ncomp=ncomp.pls1se)
pls.rmsep = RMSE(pls.preds, log(test$early_career_pay))
```

For the report/supplemental:
- Include this linear regression and explain why this model is insufficient
  (i.e., consider other models)

Other Models:
- LASSO and/or PLSR/PCR (dim. red. approaches)
- Nonlinear?
- Novel model :p